import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from '../app/components/Footer'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Select the weights you need
  variable: "--font-poppins", // This creates a CSS variable
});

export const metadata: Metadata = {
  title: "TalesFM-Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  antialiased`}>
        <Navbar />
        {children}
        <Footer footer={null} />
      </body>
    </html>
  );
}
